
baseURL: "https://adejumoridwan.com"
title: adejumo999@gmail.com
paginate: 5
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: "https://media-exp1.licdn.com/dms/image/C4D03AQEtiGiNfj-Jkg/profile-displayphoto-shrink_800_800/0/1582301185493?e=1652313600&v=beta&t=er5BtbpNkCrv_ze6E1dS2hWA4Iw_H5-NNygdvTXNafs"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Adejumo Ridwan Suleiman
    subtitle: "Statistical/Data Analyst"
    imageUrl: "https://media-exp1.licdn.com/dms/image/C4D03AQEtiGiNfj-Jkg/profile-displayphoto-shrink_800_800/0/1582301185493?e=1652313600&v=beta&t=er5BtbpNkCrv_ze6E1dS2hWA4Iw_H5-NNygdvTXNafs"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image
    buttons:
      - name: About
        url: /about/
      - name: Blog
        url: /blog/
      - name: Projects
        url: /projects/
      - name: CV
        url: "/file/resume_Adejumo_Ridwan_Suleiman.pdf/"
      - name: Rbloggers
        url: "https://www.r-bloggers.com/"
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/RidwanAdejumoS1"
    - name: linkedin
      url: "https://www.linkedin.com/in/ridwan-adejumo-suleiman-03461a178/"
    - name: github
      url: "https://github.com/adejumoridwan"
    - name: cv
      url: "/file/resume_Adejumo_Ridwan_Suleiman.pdf"

      


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
#menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

