
baseURL: "https://adejumoridwan.com"
title: Adejumo Ridwan Suleiman
paginate: 5
favicon: "https://cdn3.iconfinder.com/data/icons/flat-icons-web/40/Bargraph-512.png"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "https://cdn-icons-png.flaticon.com/512/3094/3094918.png"
    favicon16x16: "https://cdn-icons-png.flaticon.com/512/3094/3094918.png"
    favicon32x32: "https://cdn-icons-png.flaticon.com/512/3094/3094918.png"
    apple_touch_icon: "https://cdn-icons-png.flaticon.com/512/3094/3094918.png"
    safari_pinned_tab: "https://cdn-icons-png.flaticon.com/512/3094/3094918.png"

  label:
    text: "Home"
    icon: "https://cdn-icons-png.flaticon.com/512/3094/3094918.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Adejumo Ridwan Suleiman
    subtitle: "Data Analytics Consultant || Statistician"
    imageUrl: "https://www.adejumoridwan.com/about/about-me/images/d.jpg"
    imageWidth: 250
    imageHeight: 250
    imageTitle: my image
    buttons:
      - name: Abouts
        url: /about/
      - name: Blog
        url: /blog/
      - name: Projects
        url: /projects/
      #- name: CV
       # url: "/file/resume_Adejumo_Ridwan_Suleiman.pdf/"
      - name: Courses
        url: "/courses/"
      - name: Rbloggers
        url: "https://www.r-bloggers.com/"
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/RidwanAdejumoS1"
    - name: linkedin
      url: "https://www.linkedin.com/in/ridwan-adejumo-suleiman-03461a178/"
    - name: github
      url: "https://github.com/adejumoridwan"
    #- name: cv
      #url: "/file/resume_Adejumo_Ridwan_Suleiman.pdf"
    - name: rss
      url: "https://adejumoridwan.com/index.xml"

      


  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  #editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
#menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: example
      name: example.org
      url: https://example.org
      weight: 30
      
  output:
    home:
        -HTML
        -RSS
        -JSON
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

