---
title: Excel:Beginner To Advanced
author: Adejumo Ridwan Suleiman
date: '2022-04-10'
slug: []
categories:
  - excel
  - Data Analysis
  - business analysis
  - data visualization
tags: []
---

Excel is a spreadsheet program developed by Microsoft that organizes data into rows and columns and allows users to perform mathematical operations. Excel is typically used for: 

- Data Analysis  
- Data Entry
- Data Management 
- Accounting
- Budgeting 
- Data Visualization
- Programming
- Financial Modelling
- And much more!

Excel is easy to learn, get started and also user friendly. It has maintained its reputation for years as the most popular spreadsheet program in the world. 

In this course, we take a look at excel from a beginner's perspective to familiarize ourselves with the excel window.

### Who is this course for:
- Those who want to start a career in the field of data analytics.
- Those who have basic backgrounds in excel and want to broaden their knowledge.

### Course Outcome:
- Trainees at the end of this course should be able to build insightful dashboards from datasets.
- Trainess should be able to perform complex mathematical operations.

### Course Outline:
#### Excel Introduction
- Excel Getting Started
- Excel Overview
- Excel Syntax
- Excel Ranges
- Excel Fill
- Excel Move Cells
- Excel Add Cells
- Excel Delete Cells
- Excel Undo Redo

#### Excel Formatting
- Excel Format Painter
- Excel Format Colors
- Excel Format Fonts
- Excel Format Borders
- Excel Format Numbers
- Excel Format Grids
- Excel Format Settings

#### Excel Data Analysis
- Excel Sort
- Excel Filter 
- Excel Tables
- Excel Conditional Format 
- Excel Highlight Cell Rules
- Excel Top Bottom Rules
- Excel Data Bars
- Excel Color Scales
- Excel Icon Sets
- Excel Icon Sets
- Excel Manage Rules
- Excel Charts
- Excel Charts Customization
- Excel Pivot Table

#### Excel Functions
AND, AVERAGE, AVERAGEIF, AVERAGEIFS, COUNT, COUNTA, COUNTBLANK, COUNTIF, COUNTIFS, IF, IFS, MAX, MEDIAN, MIN, MODE, OR, STDEV.P, STDEV.S, SUM, SUMIF, SUMIFS, VLOOKUP, XOR

#### Excel Capstone Project
- Case Study 1: Netflix Dataset
- Case Study 2: Nigerian Used Car Market


